# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_address: <%= ENV["MAILER_EMAIL_ADDRESS"] %>

test:
  secret_key_base: fbe33a5bb866f73e88d0d94c564338d47a84625962a58ba1ecfe99e9f8e497e773910a88ea31657e40fc90ee2d832223c771ca8627d32e755bcc5deb8ff0c978
  mailer_address: noreply@example.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_address: <%= ENV["MAILER_EMAIL_ADDRESS"] %>
